"""CharacterDatabase with 50+ mythological characters."""
from __future__ import annotations
from ..models import Character, Source


class CharacterDatabase:
    """Database of 50+ mythological characters with descriptions."""

    def __init__(self) -> None:
        self._characters: list[Character] = self._load_characters()

    def _load_characters(self) -> list[Character]:
        return [
            Character(name="Rama", aliases=["Ramachandra", "Raghava", "Dasharathi"], description="The ideal king, seventh avatar of Vishnu. Embodies dharma, duty, and righteousness.", role="hero", source=[Source.RAMAYANA], relationships={"Sita": "wife", "Lakshmana": "brother", "Hanuman": "devotee", "Dasharatha": "father"}, key_traits=["righteous", "dutiful", "compassionate", "warrior"], weapons_items=["Kodanda bow", "Brahmastra"]),
            Character(name="Sita", aliases=["Janaki", "Vaidehi", "Maithili"], description="Daughter of the Earth, wife of Rama. Symbol of purity, strength, and devotion.", role="heroine", source=[Source.RAMAYANA], relationships={"Rama": "husband", "Janaka": "father", "Luv": "son", "Kush": "son"}, key_traits=["devoted", "strong", "pure", "patient"], weapons_items=[]),
            Character(name="Hanuman", aliases=["Bajrangbali", "Maruti", "Pawanputra"], description="Son of Vayu, supreme devotee of Rama. Embodies devotion, strength, and selfless service.", role="hero", source=[Source.RAMAYANA, Source.MAHABHARATA], relationships={"Rama": "lord", "Vayu": "father", "Anjana": "mother"}, key_traits=["devoted", "powerful", "humble", "celibate", "learned"], weapons_items=["Gada (mace)", "Sanjeevani mountain"]),
            Character(name="Ravana", aliases=["Dashakantha", "Lankeshvara"], description="Ten-headed king of Lanka. Great scholar and Shiva devotee, but undone by his desire for Sita.", role="villain", source=[Source.RAMAYANA], relationships={"Mandodari": "wife", "Kumbhakarna": "brother", "Vibhishana": "brother"}, key_traits=["powerful", "learned", "arrogant", "lustful"], weapons_items=["Chandrahasa sword", "Pushpaka Vimana"]),
            Character(name="Krishna", aliases=["Govinda", "Madhava", "Keshava", "Vasudeva"], description="Eighth avatar of Vishnu. Divine cowherd, philosopher king, and speaker of the Bhagavad Gita.", role="deity", source=[Source.MAHABHARATA, Source.BHAGAVATA_PURANA], relationships={"Radha": "beloved", "Rukmini": "wife", "Arjuna": "friend", "Devaki": "mother"}, key_traits=["playful", "wise", "strategic", "compassionate", "divine"], weapons_items=["Sudarshana Chakra", "Kaumodaki mace", "Saranga bow", "Flute"]),
            Character(name="Arjuna", aliases=["Partha", "Dhananjaya", "Gudakesha", "Savyasachin"], description="Greatest archer, third Pandava. Central figure of the Bhagavad Gita.", role="hero", source=[Source.MAHABHARATA], relationships={"Krishna": "friend/charioteer", "Draupadi": "wife", "Subhadra": "wife", "Abhimanyu": "son"}, key_traits=["skilled", "devoted", "conflicted", "brave"], weapons_items=["Gandiva bow", "Pashupatastra"]),
            Character(name="Yudhishthira", aliases=["Dharmaraja", "Ajatashatru"], description="Eldest Pandava, son of Dharma. Embodiment of truth and righteousness, but flawed by his addiction to dice.", role="hero", source=[Source.MAHABHARATA], relationships={"Draupadi": "wife", "Bhima": "brother", "Arjuna": "brother"}, key_traits=["truthful", "just", "compassionate", "weak to gambling"]),
            Character(name="Bhima", aliases=["Vrikodara", "Bhimasena"], description="Second Pandava, son of Vayu. Known for tremendous strength and appetite.", role="hero", source=[Source.MAHABHARATA], relationships={"Draupadi": "wife", "Hidimbi": "wife", "Ghatotkacha": "son"}, key_traits=["strong", "loyal", "fierce", "food-loving"], weapons_items=["Mace"]),
            Character(name="Draupadi", aliases=["Panchali", "Krishnaa", "Yajnaseni"], description="Wife of the five Pandavas. Born from sacred fire. Her humiliation sparked the great war.", role="heroine", source=[Source.MAHABHARATA], relationships={"Pandavas": "husbands", "Drupada": "father", "Krishna": "friend"}, key_traits=["fiery", "intelligent", "devotional", "strong-willed"]),
            Character(name="Karna", aliases=["Radheya", "Suryaputra", "Vasusena"], description="Secret eldest son of Kunti, raised by a charioteer. Tragic hero torn between loyalty and birth.", role="hero", source=[Source.MAHABHARATA], relationships={"Kunti": "mother", "Surya": "father", "Duryodhana": "friend"}, key_traits=["generous", "loyal", "skilled", "tragic"], weapons_items=["Vijaya bow", "Kavach-Kundal (divine armor)"]),
            Character(name="Duryodhana", aliases=["Suyodhana"], description="Eldest Kaurava. Driven by jealousy and pride, he refused to share even a needlepoint of land.", role="villain", source=[Source.MAHABHARATA], relationships={"Gandhari": "mother", "Dushasana": "brother", "Karna": "friend", "Shakuni": "uncle"}, key_traits=["ambitious", "proud", "brave", "jealous"], weapons_items=["Mace"]),
            Character(name="Bhishma", aliases=["Devavrata", "Gangaputra", "Pitamaha"], description="Grand patriarch who took a vow of lifelong celibacy. Given the boon of choosing his death.", role="mentor", source=[Source.MAHABHARATA], relationships={"Ganga": "mother", "Shantanu": "father"}, key_traits=["dutiful", "wise", "powerful", "self-sacrificing"], weapons_items=["Bow", "Iccha Mrityu (death at will)"]),
            Character(name="Drona", aliases=["Dronacharya"], description="Brahmin warrior who taught the Kuru princes. Fought for the Kauravas despite loving the Pandavas.", role="mentor", source=[Source.MAHABHARATA], relationships={"Ashwatthama": "son", "Arjuna": "favorite student"}, key_traits=["skilled teacher", "conflicted", "proud"]),
            Character(name="Shakuni", aliases=["Saubala"], description="Prince of Gandhara, maternal uncle of Duryodhana. Mastermind behind the game of dice.", role="villain", source=[Source.MAHABHARATA], relationships={"Gandhari": "sister", "Duryodhana": "nephew"}, key_traits=["cunning", "vengeful", "strategic"], weapons_items=["Loaded dice"]),
            Character(name="Shiva", aliases=["Mahadeva", "Neelakantha", "Nataraja", "Bholenath"], description="The Destroyer in the Trinity. Ascetic yogi, cosmic dancer, and compassionate lord.", role="deity", source=[Source.SHIVA_PURANA, Source.MAHABHARATA], relationships={"Parvati": "wife", "Ganesha": "son", "Kartikeya": "son"}, key_traits=["ascetic", "compassionate", "fierce", "simple"], weapons_items=["Trishul", "Damaru", "Pinaka bow"]),
            Character(name="Parvati", aliases=["Uma", "Gauri", "Shakti", "Durga"], description="Goddess of love and devotion. Shiva's eternal consort, reincarnation of Sati.", role="deity", source=[Source.SHIVA_PURANA, Source.DEVI_BHAGAVATA], relationships={"Shiva": "husband", "Ganesha": "son", "Kartikeya": "son", "Himavan": "father"}, key_traits=["devoted", "powerful", "nurturing", "determined"]),
            Character(name="Ganesha", aliases=["Ganapati", "Vinayaka", "Lambodara"], description="Elephant-headed god of beginnings and remover of obstacles. Son of Shiva and Parvati.", role="deity", source=[Source.SHIVA_PURANA, Source.SKANDA_PURANA], relationships={"Shiva": "father", "Parvati": "mother", "Kartikeya": "brother"}, key_traits=["wise", "gentle", "clever", "fond of modak"]),
            Character(name="Vishnu", aliases=["Narayana", "Hari", "Preserver"], description="The Preserver in the Trinity. Takes avatars to restore dharma whenever evil prevails.", role="deity", source=[Source.VISHNU_PURANA, Source.BHAGAVATA_PURANA], relationships={"Lakshmi": "wife", "Garuda": "mount", "Brahma": "born from navel"}, key_traits=["compassionate", "strategic", "all-pervading"], weapons_items=["Sudarshana Chakra", "Kaumodaki mace", "Shankha conch", "Padma lotus"]),
            Character(name="Lakshmi", aliases=["Sri", "Mahalakshmi", "Padma"], description="Goddess of wealth, fortune, and beauty. Eternal consort of Vishnu.", role="deity", source=[Source.VISHNU_PURANA, Source.BHAGAVATA_PURANA], relationships={"Vishnu": "husband"}, key_traits=["generous", "beautiful", "graceful"]),
            Character(name="Brahma", aliases=["Pitamaha", "Prajapati", "Creator"], description="The Creator in the Trinity. Four-faced god who created the universe and the Vedas.", role="deity", source=[Source.VISHNU_PURANA, Source.PADMA_PURANA], relationships={"Saraswati": "wife", "Vishnu": "born from navel"}, key_traits=["creative", "wise", "ancient"]),
            Character(name="Saraswati", aliases=["Vagdevi", "Bharati", "Sharada"], description="Goddess of knowledge, music, arts, and learning. Consort of Brahma.", role="deity", source=[Source.PADMA_PURANA, Source.DEVI_BHAGAVATA], relationships={"Brahma": "husband"}, key_traits=["learned", "serene", "artistic"], weapons_items=["Veena", "Book", "Mala"]),
            Character(name="Durga", aliases=["Mahishasuramardini", "Chandika", "Ambika"], description="Warrior goddess created from combined divine energies to slay Mahishasura.", role="deity", source=[Source.MARKANDEYA_PURANA, Source.DEVI_BHAGAVATA], relationships={"Shiva": "husband (as Parvati)"}, key_traits=["fierce", "protective", "powerful", "motherly"], weapons_items=["Trishul", "Chakra", "Sword", "Bow", "Lion mount"]),
            Character(name="Lakshmana", aliases=["Ramanuja", "Saumitri"], description="Rama's devoted younger brother. The model of brotherly love and selfless service.", role="hero", source=[Source.RAMAYANA], relationships={"Rama": "brother", "Urmila": "wife"}, key_traits=["devoted", "fierce", "loyal", "selfless"]),
            Character(name="Vibhishana", aliases=["Bibhishan"], description="Ravana's righteous brother who chose dharma over family loyalty and joined Rama.", role="hero", source=[Source.RAMAYANA], relationships={"Ravana": "brother", "Rama": "lord"}, key_traits=["righteous", "brave", "wise"]),
            Character(name="Sugriva", description="Monkey king of Kishkindha who allied with Rama to find Sita.", role="hero", source=[Source.RAMAYANA], relationships={"Vali": "brother", "Rama": "ally"}, key_traits=["loyal", "grateful", "warrior"]),
            Character(name="Radha", aliases=["Radhika", "Radharani"], description="Krishna's beloved in Vrindavan. Represents the highest form of divine love and devotion.", role="deity", source=[Source.BHAGAVATA_PURANA, Source.PADMA_PURANA], relationships={"Krishna": "beloved"}, key_traits=["devoted", "loving", "pure"]),
            Character(name="Abhimanyu", description="Arjuna's brave son who entered the Chakravyuha knowing he could not exit.", role="hero", source=[Source.MAHABHARATA], relationships={"Arjuna": "father", "Subhadra": "mother"}, key_traits=["brave", "skilled", "young", "tragic"]),
            Character(name="Prahlada", description="Son of demon Hiranyakashipu, devoted to Vishnu since birth.", role="hero", source=[Source.BHAGAVATA_PURANA], relationships={"Hiranyakashipu": "father", "Vishnu": "lord"}, key_traits=["devoted", "fearless", "truthful"]),
            Character(name="Narada", aliases=["Devarishi Narada"], description="Divine sage who travels between worlds singing Narayana's name. Sometimes stirs up divine drama.", role="mentor", source=[Source.BHAGAVATA_PURANA, Source.VISHNU_PURANA], relationships={"Vishnu": "lord"}, key_traits=["devotional", "mischievous", "wise"], weapons_items=["Veena", "Mantra chanting"]),
            Character(name="Dasharatha", description="King of Ayodhya, father of Rama. Bound by his word, he sent his beloved son to exile.", role="hero", source=[Source.RAMAYANA], relationships={"Rama": "son", "Kausalya": "wife", "Kaikeyi": "wife"}, key_traits=["noble", "truthful", "loving father"]),
            Character(name="Gandhari", description="Queen of Hastinapura who blindfolded herself for life to share her blind husband's world.", role="heroine", source=[Source.MAHABHARATA], relationships={"Dhritarashtra": "husband", "Duryodhana": "son", "Shakuni": "brother"}, key_traits=["devoted", "self-sacrificing", "suffering"]),
            Character(name="Kunti", aliases=["Pritha"], description="Mother of three Pandavas, who bore Karna secretly before marriage.", role="heroine", source=[Source.MAHABHARATA], relationships={"Karna": "son", "Yudhishthira": "son", "Bhima": "son", "Arjuna": "son"}, key_traits=["wise", "protective", "burdened by secrets"]),
            Character(name="Vidura", description="Wise minister of Hastinapura, incarnation of Dharma. Always spoke truth to power.", role="mentor", source=[Source.MAHABHARATA], relationships={"Pandavas": "protector"}, key_traits=["wise", "just", "diplomatic"]),
            Character(name="Bhagiratha", description="King who brought Ganga to earth through centuries of penance.", role="hero", source=[Source.BHAGAVATA_PURANA], relationships={"Ganga": "brought to earth"}, key_traits=["determined", "devoted", "persistent"]),
            Character(name="Savitri", description="Princess who outwitted Yama to bring her husband back from death.", role="heroine", source=[Source.MAHABHARATA], relationships={"Satyavan": "husband"}, key_traits=["intelligent", "devoted", "brave"]),
            Character(name="Dhruva", description="Five-year-old prince who became the Pole Star through meditation.", role="hero", source=[Source.BHAGAVATA_PURANA], relationships={"Vishnu": "lord"}, key_traits=["determined", "devotional", "young"]),
            Character(name="Kartikeya", aliases=["Murugan", "Skanda", "Subramanya"], description="God of war, son of Shiva and Parvati. Commander of the divine army.", role="deity", source=[Source.SKANDA_PURANA], relationships={"Shiva": "father", "Parvati": "mother", "Ganesha": "brother"}, key_traits=["brave", "youthful", "warrior"], weapons_items=["Vel (spear)"]),
            Character(name="Yama", aliases=["Dharmaraja", "Kala"], description="God of death and justice. Judges souls based on their karma.", role="deity", source=[Source.GARUDA_PURANA], key_traits=["just", "stern", "impartial"], weapons_items=["Noose", "Buffalo mount"]),
            Character(name="Indra", aliases=["Devendra", "Shakra", "Purandara"], description="King of the gods and lord of heaven. Often jealous and insecure about his throne.", role="deity", source=[Source.BHAGAVATA_PURANA], key_traits=["powerful", "jealous", "generous when pleased"], weapons_items=["Vajra thunderbolt", "Airavata elephant"]),
            Character(name="Agni", description="God of fire. Messenger between humans and gods through sacrificial offerings.", role="deity", source=[Source.BHAGAVATA_PURANA], key_traits=["purifying", "all-consuming", "truthful"]),
            Character(name="Surya", aliases=["Aditya", "Ravi"], description="The Sun God. Father of Karna and Sugriva. Source of light and life.", role="deity", source=[Source.BHAGAVATA_PURANA], relationships={"Karna": "son", "Sugriva": "son"}, key_traits=["radiant", "disciplined", "life-giving"]),
            Character(name="Parashurama", aliases=["Bhargava Rama"], description="Sixth avatar of Vishnu. Warrior Brahmin who annihilated Kshatriyas twenty-one times.", role="hero", source=[Source.BHAGAVATA_PURANA, Source.MAHABHARATA], relationships={"Jamadagni": "father"}, key_traits=["fierce", "just", "uncompromising"], weapons_items=["Parashu (axe)"]),
            Character(name="Narasimha", description="Half-man half-lion avatar of Vishnu who killed Hiranyakashipu.", role="deity", source=[Source.BHAGAVATA_PURANA], relationships={"Prahlada": "protected"}, key_traits=["fierce", "protective", "terrifying to evil"]),
            Character(name="Vamana", description="Dwarf Brahmin avatar of Vishnu who measured the universe in three steps.", role="deity", source=[Source.BHAGAVATA_PURANA], relationships={"Mahabali": "tested"}, key_traits=["humble appearance", "cosmic power"]),
            Character(name="Ekalavya", description="Tribal archer whose devotion to his guru led him to sacrifice his thumb.", role="hero", source=[Source.MAHABHARATA], relationships={"Drona": "guru (self-chosen)"}, key_traits=["devoted", "self-taught", "tragic"]),
            Character(name="Jatayu", description="Aged vulture king who fought Ravana to protect Sita.", role="hero", source=[Source.RAMAYANA], relationships={"Rama": "friend of father"}, key_traits=["brave", "self-sacrificing", "loyal"]),
            Character(name="Mandodari", description="Ravana's virtuous wife who repeatedly counseled him to return Sita.", role="heroine", source=[Source.RAMAYANA], relationships={"Ravana": "husband"}, key_traits=["wise", "virtuous", "long-suffering"]),
            Character(name="Ashwatthama", description="Drona's son, cursed to immortality for his crimes. Wanders eternally.", role="villain", source=[Source.MAHABHARATA], relationships={"Drona": "father"}, key_traits=["powerful", "vengeful", "cursed"]),
            Character(name="Ghatotkacha", description="Son of Bhima and Hidimbi. Half-rakshasa warrior who fought for the Pandavas.", role="hero", source=[Source.MAHABHARATA], relationships={"Bhima": "father", "Hidimbi": "mother"}, key_traits=["powerful", "loyal", "self-sacrificing"]),
            Character(name="Vyasa", aliases=["Vedavyasa", "Krishna Dvaipayana"], description="Author of the Mahabharata and compiler of the Vedas. Grandfather of Pandavas and Kauravas.", role="mentor", source=[Source.MAHABHARATA], relationships={"Parasara": "father", "Satyavati": "mother"}, key_traits=["omniscient", "wise", "literary genius"]),
        ]

    def get_all_characters(self) -> list[Character]:
        return self._characters

    def get_character(self, name: str) -> Character | None:
        name_lower = name.lower()
        for c in self._characters:
            if name_lower == c.name.lower() or any(name_lower == a.lower() for a in c.aliases):
                return c
        return None

    def search_characters(self, query: str) -> list[Character]:
        q = query.lower()
        return [c for c in self._characters if q in c.name.lower() or q in c.description.lower()
                or any(q in a.lower() for a in c.aliases)]

    def get_by_role(self, role: str) -> list[Character]:
        return [c for c in self._characters if c.role == role]

    def get_by_source(self, source: Source) -> list[Character]:
        return [c for c in self._characters if source in c.source]

    def get_character_count(self) -> int:
        return len(self._characters)
